### ISSUE TITLE
Benchmark measures wrong operations

### ISSUE THREAD

**Issue by neon-sunset** [ayan4m1/ForBenchmark#1]
This repo has showed up on my recommendations so I thought it might be worthwhile to chime in as the benchmark appears to have a common mistake people make when working with arrays.
- ForIndex reads an array from a private field on each iteration
- ForEach stores an array in a method local
- Reading `byte` elements one by one is not as through-put efficient as working with larger primitive element sizes like int or long. It's not "faster" per se but you can get more work done when packing data into larger numeric types.

Because JIT cannot guarantee that `data` reference has not been changed between iterations, writing to it involves two extra operations which are reading an object reference from a field and performing a bounds check. By storing `data` to a local `var local = data` this resolves the issue and makes behavior logically consistent with that of `foreach`.

p.s.: you can further improve LINQ performance by enabling Dynamic PGO via either .csproj property `<TieredPGO>true</TieredPGO>` or env var `DOTNET_TieredPGO=1`.

**Comment by ayan4m1** [comment]
Thanks, I just put this together to show the futility of trying to make a comprehensive benchmark for such a broad use case. Someone on Reddit pointed out the second access and I amended it, now ForEach and ForIndex are roughly neck-and-neck, but I'm not actually concerned with making these benchmarks run as quickly as possible. Sorry, I didn't intend for this repo to show up in anyone's recommendations.
